ORDERINITED = 1
ORDERSENDED = 2
ORDERFILLED = 3
ORDERERROR = 4

LONGIDX = 1
SHORTIDX = 2

SIDEBYIDX = {LONGIDX: "Buy",
             SHORTIDX: "Sell"}

IDXBYSIDE = {"Buy": LONGIDX, 
             "Sell": SHORTIDX}